---
title: "Quantile Dists"
author: "Joel Eliason"
date: "2023-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DIMPLE)
library(tidyverse)
```

```{r}
# Create an experiment with intensities, distance matrices and patient metadata
set.seed(1234)
N <- 30000
n_slides <- 30
cell_x_values = runif(N, 0, 600)
cell_y_values = runif(N, 0, 600)
cell_marks = sample(c("Tumor", "Immune", "Stroma","Other"), N, replace = TRUE)
slide_ids = rep(paste("Slide", 1:n_slides), each = 1000)

slides <- unique(slide_ids)
n_patients <- 10
n_groups <- 2
patient_ids <- rep_len(paste0("P",1:n_patients),n_slides)

metadata <- tibble::tibble(slide_id=slides,
                   patient_id=patient_ids)

groups <- sample(rep_len(sample(paste0("G",1:n_groups)),n_patients))

ages <- runif(n_patients,min=45,max=100)

gp_tb <- tibble::tibble(patient_id=unique(patient_ids),group=groups,age=ages)
metadata <- dplyr::left_join(metadata,gp_tb,by = "patient_id")
print(metadata)

mltplx_experiment = new_MltplxExperiment(x = cell_x_values,
                                  y = cell_y_values,
                                  marks = factor(cell_marks),
                                  slide_id = slide_ids,
                                  ps = 30, bw = 40,
                                  dist_metric = jsd,
                                  metadata = metadata)
q_probs <- tibble(from=c(0,34,67),to=c(33,66,100))
mltplx_experiment <- update_qdist(mltplx_experiment,
                                  jsd,
                                  "Tumor",
                                  q_probs)

mltplx_experiment
```

```{r}
mltplx_experiment %>%
  plot_ppp(slide_ids = c("Slide 12","Slide 13"))
```

```{r}
mltplx_experiment %>%
  plot_intensity_surface(types = c("Tumor","Stroma"),
                   slide_ids = c("Slide 7","Slide 9"))

```

```{r}
mltplx_experiment %>%
  patient_boxplots(t1="Tumor",t2="Immune",grouping_var = "group",p_val_col = "p.adj")
```

```{r}
mltplx_experiment %>%
  plot_dist_boxplots(t1 = "Stroma",
                    t2 = "Immune",
                    grouping_var = "group",
                    agg_fun = median)
```

```{r}
mltplx_experiment %>%
  plot_dist_scatter(t1 = "Stroma",
                    t2 = "Immune",
                    cont_var = "age",
                    agg_fun = median,
                    smooth = "lm")
```

```{r}
mltplx_experiment %>%
  plot_dist_matrix(slide_ids = c("Slide 1", "Slide 2","Slide 3"),mode="network")
```

```{r}
mltplx_experiment %>%
  plot_dist_matrix(slide_ids = c("Slide 1", "Slide 2","Slide 3"),mode="heatmap")
```

```{r}
mltplx_experiment %>%
  lm_dist("group",
          covariates = c("age")) %>%
  plot_dist_regression_heatmap()
```


## Quantile-based analyses

```{r}
mltplx_experiment %>%
  patient_boxplots_qdist(t1="Tumor",t2="Immune",grouping_var = "group")
```

```{r}
mltplx_experiment %>%
  plot_qdist_boxplots(t1 = "Stroma",
                    t2 = "Immune",
                    grouping_var = "group",
                    agg_fun = median)
```

```{r}
mltplx_experiment %>%
  plot_qdist_scatter(t1 = "Stroma",
                    t2 = "Immune",
                    cont_var = "age",
                    agg_fun = median,
                    smooth = "lm")
```

```{r}
mltplx_experiment %>%
  plot_qdist_matrix(slide_ids = c("Slide 1", "Slide 2","Slide 3"),mode="heatmap")
```

```{r}
mltplx_experiment %>%
  lm_qdist("group",
           interval = "67-100",
          covariates = c("age")) %>%
  plot_dist_regression_heatmap()
```

